name: plantcare
description: 绿植管家 —— 治愈系绿植养护 App（设计稿高保真还原）
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  video_player: ^2.9.1
  http: ^1.2.2
  intl: ^0.19.0
  flutter_tts: 3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/MiSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/MiSans-Demibold.ttf
          weight: 600
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 900
